[package]
name = "shy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lucian = "0.2"
[patch.crates-io]
lucian = { path = '../lucian' }
